application: uuedvalimised
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /main
  script: valimised.main

- url: /index
  script: valimised.index

- url: /myjson
  script: valimised.myjson

- url: /myjson/stat
  script: valimised.mystat

- url: /myjson/vote
  script: valimised.myvote

- url: /Images
  static_dir: Images

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /json_temp
  static_dir: json_temp

libraries:
- name: lxml
  version: latest
