application: uuedvalimised
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

#- url: /static/(.*\.appcache)
#  static_files: static/\1
#  mime_type: text/cache-manifest
#  upload: static/(.*\.appcache)

# Static files
- url: /Images
  static_dir: Images

- url: /js
  static_dir: js

- url: /css
  static_dir: css

# Facebook

- url: /.*
  script: valimised.app

# toDepriciate

- url: /main
  script: valimised.main

- url: /index
  script: valimised.index

# JSON requests

- url: /myjson
  script: valimised.myjson

- url: /myjson/stat
  script: valimised.mystat

- url: /myjson/vote
  script: valimised.myvote

# Testing

- url: /json_temp
  static_dir: json_temp
  
# Channel api
inbound_services:
- channel_presence

libraries:
- name: lxml
  version: latest

- name: jinja2
  version: latest
